# Generated by Django 5.2.17 on 2026-08-15 07:12

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlantCultivar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("cultivar_name", models.CharField(blank=True, max_length=160)),
                ("display_name", models.CharField(max_length=160)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tree", "Tree"),
                            ("shrub", "Shrub"),
                            ("flower", "Flower"),
                            ("groundcover", "Groundcover"),
                            ("grass", "Grass"),
                        ],
                        max_length=20,
                    ),
                ),
                ("growth_habit", models.CharField(blank=True, max_length=80)),
                (
                    "mature_height_min_m",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
                ),
                (
                    "mature_height_max_m",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
                ),
                (
                    "canopy_radius_m",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "recommended_spacing_m",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "root_caution_radius_m",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "structure_clearance_m",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("sunlight", models.JSONField(default=list)),
                (
                    "water_need",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "liters_per_week_estimate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("style_tags", models.JSONField(default=list)),
                ("color", models.CharField(default="#6f8f61", max_length=7)),
                (
                    "provenance",
                    models.CharField(default="prototype_unverified", max_length=40),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("display_name",),
            },
        ),
        migrations.CreateModel(
            name="PlantSpecies",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("scientific_name", models.CharField(max_length=180, unique=True)),
                ("family", models.CharField(blank=True, max_length=120)),
                ("genus", models.CharField(blank=True, max_length=120)),
                ("common_names", models.JSONField(default=dict)),
                (
                    "origin_chile",
                    models.CharField(
                        choices=[
                            ("native", "Native"),
                            ("endemic", "Endemic"),
                            ("exotic", "Exotic"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("conservation_status", models.CharField(blank=True, max_length=60)),
                ("is_invasive", models.BooleanField(default=False)),
                ("is_restricted", models.BooleanField(default=False)),
                ("source_references", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ("scientific_name",),
            },
        ),
        migrations.CreateModel(
            name="PlantRuleVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                ("context", models.JSONField(default=dict)),
                ("rules", models.JSONField(default=list)),
                ("source_url", models.URLField(blank=True)),
                ("source_label", models.CharField(blank=True, max_length=180)),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.5,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cultivar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_versions",
                        to="catalog.plantcultivar",
                    ),
                ),
            ],
            options={
                "ordering": ("cultivar", "-version"),
            },
        ),
    ]
