# Generated by Django 5.2.17 on 2026-08-15 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plantruleversion",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_plant_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="plantcultivar",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cultivars",
                to="catalog.plantspecies",
            ),
        ),
        migrations.AddConstraint(
            model_name="plantruleversion",
            constraint=models.UniqueConstraint(
                fields=("cultivar", "version"), name="catalog_unique_rule_version"
            ),
        ),
        migrations.AddIndex(
            model_name="plantcultivar",
            index=models.Index(
                fields=["category", "is_active", "display_name"],
                name="catalog_pla_categor_106986_idx",
            ),
        ),
    ]
