# Generated by Django 5.2.17 on 2026-08-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantcultivar",
            name="color_winter",
            field=models.CharField(
                blank=True,
                help_text="Stem/branch color in winter (for deciduous plants)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="plantcultivar",
            name="foliage_type",
            field=models.CharField(
                choices=[
                    ("evergreen", "Evergreen"),
                    ("deciduous", "Deciduous (loses leaves in winter)"),
                    ("semi_deciduous", "Semi-deciduous (partial loss)"),
                ],
                default="evergreen",
                max_length=20,
            ),
        ),
    ]
