# Generated by Django 5.2.17 on 2026-08-27 13:20

import uuid
from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_plantcultivar_color_winter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrassSpecies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('common_name', models.CharField(max_length=160)),
                ('scientific_name', models.CharField(blank=True, max_length=180)),
                ('liters_per_m2_week', models.DecimalField(decimal_places=3, help_text='Weekly water consumption per m² (referential, non-production)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('sunlight', models.CharField(choices=[('full_sun', 'Full sun (6+ hours)'), ('partial_shade', 'Partial shade (3-6 hours)'), ('shade', 'Shade (<3 hours)')], max_length=20)),
                ('foot_traffic_resistance', models.CharField(choices=[('low', 'Low (not suitable for foot traffic)'), ('medium', 'Medium (suitable for light use)'), ('high', 'High (suitable for heavy use)')], max_length=20)),
                ('seasonality', models.CharField(blank=True, help_text="Seasonal behavior (e.g., 'winter dormant', 'year-round green')", max_length=80)),
                ('source', models.CharField(help_text='Source of data (URL, publication, etc.)', max_length=180)),
                ('valid_from', models.DateField(help_text='Date when this data became valid')),
                ('provenance', models.CharField(default='prototype_unverified', max_length=40)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('common_name',),
            },
        ),
    ]
