# Generated by Django 5.2.17 on 2026-08-15 07:12

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("discovery", "Discovery"),
                            ("design", "Design"),
                            ("review", "Review"),
                            ("approved", "Approved"),
                            ("archived", "Archived"),
                        ],
                        default="discovery",
                        max_length=20,
                    ),
                ),
                (
                    "output_level",
                    models.CharField(
                        choices=[
                            ("L0", "Concept"),
                            ("L1", "Preliminary"),
                            ("L2", "Technical"),
                        ],
                        default="L0",
                        max_length=2,
                    ),
                ),
                ("currency", models.CharField(default="CLP", max_length=3)),
                (
                    "budget_min",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "budget_max",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="identity.client",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="identity.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("commune", models.CharField(blank=True, max_length=120)),
                ("region", models.CharField(blank=True, max_length=120)),
                ("country", models.CharField(default="CL", max_length=2)),
                ("address", models.CharField(blank=True, max_length=250)),
                (
                    "location_precision",
                    models.CharField(default="approximate", max_length=20),
                ),
                (
                    "timezone",
                    models.CharField(default="America/Santiago", max_length=64),
                ),
                ("water_provider_name", models.CharField(blank=True, max_length=160)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveIntegerField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("reported", "Client reported"),
                            ("drawn", "Drawn in editor"),
                            ("calibrated", "Calibrated plan"),
                            ("survey", "Professional survey"),
                        ],
                        default="reported",
                        max_length=20,
                    ),
                ),
                (
                    "width_m",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                    ),
                ),
                (
                    "height_m",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                    ),
                ),
                ("boundary", models.JSONField(default=dict)),
                (
                    "orientation_deg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "precision_m",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
                ),
                ("sunlight", models.CharField(default="full_sun", max_length=20)),
                (
                    "preferred_style",
                    models.CharField(default="mediterranean", max_length=30),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="projects.site",
                    ),
                ),
            ],
            options={
                "ordering": ("site", "-revision"),
            },
        ),
        migrations.CreateModel(
            name="SiteFeature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("house", "House"),
                            ("pavement", "Pavement"),
                            ("fence", "Fence"),
                            ("utility", "Utility"),
                            ("existing_plant", "Existing plant"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("geometry", models.JSONField()),
                (
                    "height_m",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
                ),
                (
                    "depth_m",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
                ),
                ("plantable", models.BooleanField(default=False)),
                ("removable", models.BooleanField(default=False)),
                ("source", models.CharField(default="client", max_length=30)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=3, default=0.5, max_digits=4),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "site_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="projects.siteversion",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["organization", "status", "updated_at"],
                name="projects_pr_organiz_791cc2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="siteversion",
            constraint=models.UniqueConstraint(
                fields=("site", "revision"), name="projects_unique_site_revision"
            ),
        ),
        migrations.AddIndex(
            model_name="sitefeature",
            index=models.Index(
                fields=["site_version", "feature_type"],
                name="projects_si_site_ve_4285dd_idx",
            ),
        ),
    ]
