# Generated by Django 5.2.17 on 2026-08-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_siteversion_height_m_alter_siteversion_width_m"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitefeature",
            name="liters_per_m2_week",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Weekly water consumption per m² (lawn zones only)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitefeature",
            name="water_need",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                help_text="Water need for lawn zones",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitefeature",
            name="feature_type",
            field=models.CharField(
                choices=[
                    ("house", "House"),
                    ("pavement", "Pavement"),
                    ("fence", "Fence"),
                    ("utility", "Utility"),
                    ("existing_plant", "Existing plant"),
                    ("lawn_zone", "Lawn zone"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
