# Generated by Django 5.2.17 on 2026-08-27 02:19

from django.db import migrations


def convert_rect_to_polygon(apps, schema_editor):
    """Convert rectangle geometry to polygon format.

    Existing rect features with {x, y, width, height} become
    {type: "polygon", points: [{x,y}, ...]}.
    Features without explicit type are assumed to be rectangles.
    """
    SiteFeature = apps.get_model("projects", "SiteFeature")

    for feature in SiteFeature.objects.all():
        geom = feature.geometry
        if not isinstance(geom, dict):
            continue

        geom_type = geom.get("type")
        if geom_type == "polygon":
            continue

        required = ("x", "y", "width", "height")
        if all(k in geom for k in required):
            x = geom["x"]
            y = geom["y"]
            w = geom["width"]
            h = geom["height"]

            feature.geometry = {
                "type": "polygon",
                "points": [
                    {"x": x, "y": y},
                    {"x": x + w, "y": y},
                    {"x": x + w, "y": y + h},
                    {"x": x, "y": y + h},
                ],
            }
            feature.save(update_fields=["geometry"])


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_sitefeature_liters_per_m2_week_and_more"),
    ]

    operations = [
        migrations.RunPython(convert_rect_to_polygon),
    ]
