# Generated by Django 5.2.17 on 2026-08-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_convert_rect_to_polygon'),
    ]

    operations = [
    ]
