# Generated by Django 5.2.17 on 2026-08-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_non_plantable_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefeature',
            name='feature_type',
            field=models.CharField(choices=[('house', 'House'), ('pavement', 'Pavement'), ('fence', 'Fence'), ('utility', 'Utility'), ('existing_plant', 'Existing plant'), ('lawn_zone', 'Lawn zone'), ('pool', 'Pool'), ('quincho', 'Quincho'), ('terrace', 'Terrace'), ('path', 'Path'), ('other', 'Other')], max_length=30),
        ),
    ]
