# Generated by Django 5.2.17 on 2026-08-27 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_grassspecies'),
        ('projects', '0006_alter_sitefeature_feature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitefeature',
            name='grass_species',
            field=models.ForeignKey(blank=True, help_text='Grass species for lawn zone (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawn_zones', to='catalog.grassspecies'),
        ),
    ]
