# Generated by Django 5.2.17 on 2026-08-15 07:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0002_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Layout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("objective", models.CharField(default="balanced", max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Review"),
                            ("approved", "Approved"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("current_revision", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layouts",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ("project", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="LayoutVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Review"),
                            ("approved", "Approved"),
                            ("superseded", "Superseded"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "author_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("solver", "Solver"),
                            ("ai", "AI assistant"),
                        ],
                        default="user",
                        max_length=10,
                    ),
                ),
                (
                    "rule_set_version",
                    models.CharField(default="prototype-v1", max_length=80),
                ),
                ("engine_version", models.CharField(blank=True, max_length=80)),
                ("input_snapshot", models.JSONField(default=dict)),
                ("result_summary", models.JSONField(default=dict)),
                ("canonical_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="layout_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="planning.layout",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="planning.layoutversion",
                    ),
                ),
                (
                    "site_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="layout_versions",
                        to="projects.siteversion",
                    ),
                ),
            ],
            options={
                "ordering": ("layout", "-revision"),
            },
        ),
        migrations.CreateModel(
            name="LayoutItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stable_id", models.UUIDField(default=uuid.uuid4)),
                ("x_m", models.DecimalField(decimal_places=3, max_digits=10)),
                ("y_m", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "rotation_deg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "scale",
                    models.DecimalField(decimal_places=3, default=1, max_digits=6),
                ),
                ("stage", models.CharField(default="mature", max_length=20)),
                ("is_locked", models.BooleanField(default=False)),
                ("source", models.CharField(default="solver", max_length=20)),
                ("overrides", models.JSONField(blank=True, default=dict)),
                (
                    "cultivar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="layout_items",
                        to="catalog.plantcultivar",
                    ),
                ),
                (
                    "layout_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="planning.layoutversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolverRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("algorithm", models.CharField(default="grid-v2", max_length=80)),
                ("random_seed", models.BigIntegerField(default=0)),
                ("input_hash", models.CharField(db_index=True, max_length=64)),
                ("score", models.JSONField(blank=True, default=dict)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "layout_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solver_runs",
                        to="planning.layoutversion",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ValidationIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("blocking", "Blocking"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("accepted_exception", "Accepted exception"),
                        ],
                        default="open",
                        max_length=24,
                    ),
                ),
                ("item_ids", models.JSONField(default=list)),
                ("message", models.TextField()),
                ("conflict_geometry", models.JSONField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("acceptance_reason", models.TextField(blank=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_validation_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "layout_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_issues",
                        to="planning.layoutversion",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="layout",
            index=models.Index(
                fields=["project", "status", "updated_at"],
                name="planning_la_project_805695_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="layoutversion",
            constraint=models.UniqueConstraint(
                fields=("layout", "revision"), name="planning_unique_layout_revision"
            ),
        ),
        migrations.AddIndex(
            model_name="layoutitem",
            index=models.Index(
                fields=["layout_version", "cultivar"],
                name="planning_la_layout__7eae8c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="layoutitem",
            constraint=models.UniqueConstraint(
                fields=("layout_version", "stable_id"),
                name="planning_unique_item_stable_id",
            ),
        ),
        migrations.AddIndex(
            model_name="solverrun",
            index=models.Index(
                fields=["status", "created_at"], name="planning_so_status_388072_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validationissue",
            index=models.Index(
                fields=["layout_version", "status", "severity"],
                name="planning_va_layout__914f8e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationissue",
            index=models.Index(fields=["code", "status"], name="planning_va_code_7e624a_idx"),
        ),
    ]
