# Generated by Django 5.2.17 on 2026-08-15 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        ("identity", "0001_initial"),
        ("planning", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pricebook",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_books",
                to="identity.organization",
            ),
        ),
        migrations.AddField(
            model_name="priceitem",
            name="price_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="finance.pricebook",
            ),
        ),
        migrations.AddField(
            model_name="projectbudget",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectbudget",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="price_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quote_items",
                to="finance.priceitem",
            ),
        ),
        migrations.AddField(
            model_name="quoteversion",
            name="layout_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotes",
                to="planning.layoutversion",
            ),
        ),
        migrations.AddField(
            model_name="quoteversion",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="finance.quoteversion",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["project", "status", "expense_date"],
                name="finance_exp_project_2d89ac_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricebook",
            constraint=models.UniqueConstraint(
                fields=("organization", "name", "version"),
                name="finance_unique_price_book",
            ),
        ),
        migrations.AddConstraint(
            model_name="priceitem",
            constraint=models.UniqueConstraint(
                fields=("price_book", "code"), name="finance_unique_price_item_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="quoteversion",
            constraint=models.UniqueConstraint(
                fields=("project", "version"), name="finance_unique_quote_version"
            ),
        ),
    ]
