# Generated by Django 5.2.17 on 2026-08-15 07:12

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("country", models.CharField(default="CL", max_length=2)),
                ("service_regions", models.JSONField(default=list)),
                ("website", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="IrrigationZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("geometry", models.JSONField(default=dict)),
                ("emitter_type", models.CharField(default="drip", max_length=80)),
                (
                    "target_flow_l_min",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "efficiency",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.85,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("schedule", models.JSONField(blank=True, default=dict)),
                (
                    "layout_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irrigation_zones",
                        to="planning.layoutversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TariffVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "fixed_charge_clp",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "potable_water_clp_per_m3",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "sewer_clp_per_m3",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "peak_surcharge_clp_per_m3",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "overconsumption_threshold_m3",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
                ),
                ("source_url", models.URLField()),
                ("source_label", models.CharField(max_length=200)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariffs",
                        to="irrigation.waterprovider",
                    ),
                ),
            ],
            options={
                "ordering": ("provider", "-effective_from"),
            },
        ),
        migrations.CreateModel(
            name="IrrigationEstimate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scenario", models.CharField(default="baseline", max_length=30)),
                ("weekly_liters", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "monthly_cubic_meters",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "low_monthly_cubic_meters",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "high_monthly_cubic_meters",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "incremental_cost_clp",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "projected_bill_cost_clp",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                ("assumptions", models.JSONField(default=dict)),
                ("confidence", models.CharField(default="prototype", max_length=20)),
                (
                    "layout_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irrigation_estimates",
                        to="planning.layoutversion",
                    ),
                ),
                (
                    "tariff_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estimates",
                        to="irrigation.tariffversion",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("layout_version", "scenario"),
                        name="irrigation_unique_estimate_scenario",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tariffversion",
            constraint=models.UniqueConstraint(
                fields=("provider", "effective_from"),
                name="irrigation_unique_tariff_start",
            ),
        ),
    ]
