# Generated by Django 5.2.17 on 2026-08-15 07:23

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("irrigation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="irrigationzone",
            name="efficiency",
            field=models.DecimalField(
                decimal_places=3,
                default=0.85,
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.1")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
            ),
        ),
    ]
