# Generated by Django 5.2.17 on 2026-08-26 20:08

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("irrigation", "0002_alter_irrigationzone_efficiency"),
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IrrigationNetworkDesign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "water_source_x",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "water_source_y",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "main_pipe_route",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of {x, y} points defining the main pipe path",
                    ),
                ),
                (
                    "num_main_pipes",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "layout",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irrigation_network_design",
                        to="planning.layout",
                    ),
                ),
                (
                    "zones",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Zones served by this network design",
                        related_name="network_designs",
                        to="irrigation.irrigationzone",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
