# Generated by Django 5.2.17 on 2026-08-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("irrigation", "0003_irrigationnetworkdesign"),
    ]

    operations = [
        migrations.AddField(
            model_name="irrigationnetworkdesign",
            name="water_source_type",
            field=models.CharField(
                choices=[
                    ("potable", "Potable (red pública)"),
                    ("well", "Well (pozo)"),
                    ("rainwater", "Rainwater (recolección)"),
                    ("grey", "Grey water (reutilizada)"),
                ],
                default="potable",
                max_length=20,
            ),
        ),
    ]
